import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import MobileNavbar from "@/components/employerViewComponents/MobileNavbar";
import Topbar from "@/components/employerViewComponents/Topbar";
import Sidebar from "@/components/employerViewComponents/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function EmployerRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* MOBILE VIEW */}
          <div className="flex flex-col lg:hidden">
            <MobileNavbar />
            {children}
          </div>

          {/* DESKTOP VIEW */}
          <div className="hidden lg:flex lg:h-screen">
            <Sidebar />
            <div className="flex flex-col w-full">
              <Topbar />
              <div className="overflow-x-hidden overflow-y-auto h-full">{children}</div>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
